name: Ember Asset Sizes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: node -v
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: simplabs/ember-asset-size-action@update-dependencies
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
