name: Ember Asset Sizes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: Techn1x/ember-asset-size-action@boverton/edit-existing-comment
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
